"use strict";

/**
 * This optimization locates unused scopes and removes them from the IR.
 * An unused scope is a scope with no dependees
 */

var scope_optimization_template = require('./lib/scope_optimization_template');

/**
 * @param {{ scopes: Array.<Scope> }} scope_data The scope_data object generated by ir_gen
 * @returns {{ scopes: Array.<Scope> }} a cleaned version of the input scope_data
 */
function process_ir (scope_data) {
  var process = function () {};
  var verb = 'Dropped';
  return scope_optimization_template(scope_data, is_not_used, process, verb);
}

/** 
 * @param {Scope} scope The scope to check
 * @returns {boolean} Whether the scope is not used
 */
function is_not_used(scope) {
  return !scope.get_dependee_scope_count();
}

module.exports = process_ir;
